### PR TITLE
Unverified token properties no longer carry an asterisk suffix "*"

### PR DESCRIPTION
**Pull request by uschi2000**

### CODE REVIEW

**Comment by uschi2000** [comment]
@markelliot

**Comment by uschi2000** [comment]
@gracew

**Review by gracew — APPROVED** [review]
the change looks fine. where did the asterix suffix come from originally -- a palantir convention or a broader one?

**Comment by uschi2000** [comment]
mark's & my first attempt at this. thought it might make more clear that this is not the verbatim token.

**Pull request merged**
