### PR TITLE
Revert "remove json serialization annotations"

### PR DESCRIPTION
**Pull request by EthanLozano**
This reverts commit a8a475aea076ce77eda546af917207967f5d08f0.

### CODE REVIEW

**Comment by EthanLozano** [comment]
The removal of the serializer and deserializer broke my code. Specifically, I rely on the ability to serialize and deserialize an AuthHeader (in addition to using it in the header). Also, the ImmutableAuthHeader is package-private, so I don't have access to the auto-generated implementation. Would it be possible to add this code back?

**Comment by qinfchen** [comment]
`ImmutableAuthHeader` should be package-private. Why not just `AuthHeader`'s static methods to build an instance of `AuthHeader`?

**Comment by EthanLozano** [comment]
To clarify, I'm asking to bring the `@JsonSerialize` and `@JsonDeserialize` annotations back. Otherwise, it looks like I need to write a custom serializer, a custom deserializer, and register both with my object mappers during serialization and deserialization.

**Comment by qinfchen** [comment]
deferring that to @pnepywoda.

**Comment by EthanLozano** [comment]
As far as I know, the code below is the minimal amount of code that I need to regain the serialization and deserialization functionality for AuthHeader. Let me know if there is a more succinct way to regain the functionality. Alternatively, if we added the serialization/deserialization functionality back, then this extra code wouldn't be necessary.

CustomSerializableObject.java:

``` java
    @JsonSerialize(using = AuthHeaderSerializer.class)
    @JsonDeserialize(using = AuthHeaderDeserializer.class)
    private final AuthHeader authHeader;
```

AuthHeaderSerializer.java:

``` java
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.palantir.tokens.auth.AuthHeader;
import java.io.IOException;

class AuthHeaderSerializer extends StdSerializer<AuthHeader> {

    public static final String BEARER_KEY = "Bearer";

    public AuthHeaderSerializer() {
        this(null);
    }

    public AuthHeaderSerializer(Class<AuthHeader> itemClass) {
        super(itemClass);
    }

    @Override
    public void serialize(AuthHeader value, JsonGenerator gen, SerializerProvider provider) throws IOException {
        gen.writeStartObject();
        gen.writeStringField(BEARER_KEY, value.getBearerToken().getToken());
        gen.writeEndObject();
    }

}
```

AuthHeaderDeserializer.java:

``` java
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.palantir.tokens.auth.AuthHeader;
import com.palantir.tokens.auth.BearerToken;
import java.io.IOException;

class AuthHeaderDeserializer extends StdDeserializer<AuthHeader> {

    public AuthHeaderDeserializer() {
        this(null);
    }

    public AuthHeaderDeserializer(Class<?> vc) {
        super(vc);
    }

    @Override
    public AuthHeader deserialize(JsonParser jsonParser, DeserializationContext ctxt)
        throws IOException, JsonProcessingException {
        JsonNode node = jsonParser.getCodec().readTree(jsonParser);
        String bearerTokenStr = node.get(AuthHeaderSerializer.BEARER_KEY).asText();
        BearerToken bearerToken = BearerToken.valueOf(bearerTokenStr);
        return AuthHeader.of(bearerToken);
    }

}
```

**Comment by j-baker** [comment]
Hey Ethan - jackson mixins are generally good for this sort of stuff if you really need them, and save ~= all the pain you suffer from.
I guess I don't understand why you need to jsonserialise an authheader and not just the bearer token itself?
James

**Comment by pnepywoda** [comment]
I'll add the breaking change to the release notes. AuthHeader is for header information only and shouldn't ever be jackson serialized - if you need to serialize the token, read out the BearerToken

**Comment by EthanLozano** [comment]
Thanks for suggesting mixins, that is a nice alternative. I agree that serializing the bearer token is simple, but the bigger problem is that this is a backwards compatibility breaking change ( https://github.com/palantir/auth-tokens/issues/21 ). I guess I don't understand why the AuthHeader can't both be used in a header and serialized

**Comment by pnepywoda** [comment]
It's because it's fundamentally a _HEADER_ (it's for use in http headers) and NOT for serialization in a http BODY.

**Comment by markelliot** [comment]
Why aren't we just using `@JsonValue` and `@JsonCreator` here?

**Comment by markelliot** [comment]
AuthHeader is fundamentally serializable, it's just that it serializes to and from a string, not a richer json object.

**Comment by pnepywoda** [comment]
Like I said, AuthHeader is for headers and doesn't/shouldn't go through json ser-de

**Pull request closed without merging**
